// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		int iterations = Integer.parseInt(args[0]);

		int greaterCount = 0;

		for (int i = 0; i < iterations; i++) {
			if (Math.random() > 0.5) {
				greaterCount++;
			}
		}

		int lessThanCount = iterations - greaterCount;

		System.out.println("> 0.5:  " + greaterCount + " times");
		System.out.println("<= 0.5: " + lessThanCount + " times");

		if (lessThanCount != 0) {
			System.out.println("Ratio:  " + (double) greaterCount / lessThanCount);
		}
	}
}
